### PR TITLE
Micro-benchmarking setup for backing store operations

### LINKED ISSUE #44: Benchmarks for the backing store
https://github.com/input-output-hk/ouroboros-network/pull/4498 makes the LMDB backing store thread safe by using `RAWLock`s. However, we have no benchmarks at a suitable level to find out whether these changes cause performance regressions. We should write a benchmark executable at the BackingStore interface level, such that we can catch performance regression early.

### PR DESCRIPTION
**Pull request by jorisdral**
# Description

Resolves #44.

This PR introduces a micro-benchmarking setup for backing store operations. This should allows us to catch performance regressions early when we make meaningful changes to any of the backing store implementations.

Benchmark scenarios are defined as lists of commands, which are run in sequence. The commands largely coincide with the operations that the `BackingStore` and `BackingStoreValueHandle` interfaces provide. Two simple scenarios are provided as examples.

### CODE REVIEW

File: ouroboros-consensus/src/consensus-testlib/Test/Util/LedgerStateOnlyTables.hs [hunk 1]
```diff
@@ -12,23 +13,36 @@
...
+
+-- | An empty type for blocks, which is only used to record the types @k@ and
+-- @v@.
+data OTBlock k v
+
+data instance LedgerState (OTBlock k v) (mk :: MapKind) = OTLedgerState {
     otlsLedgerState  :: ValuesMK k v
-  , otlsLedgerTables :: LedgerTables (OTLedgerState k v) mk
+  , otlsLedgerTables :: OTLedgerTables k v mk
   }
```
Comment (jorisdral) [inline ouroboros-consensus/src/consensus-testlib/Test/Util/LedgerStateOnlyTables.hs:46]: INFO: We were not actually defining the `LedgerState` as a `data instance`, which this change fixes. Furthermore, since we don't want to mention the block type (it is empty anyway), we provide the `OTLedgerState` and `OTLedgerTables` type synonyms. The `OTBlock` type isn't exported.

File: ouroboros-consensus/bench/backingstore-bench/Bench/Commands.hs [hunk 2]
```diff
@@ -0,0 +1,221 @@
...
+  | BSVHClose        !VHID
+  | BSVHRangeRead    !VHID !(RangeQuery ks)
+  | BSVHRead         !VHID !ks
+  | BSRead           !ks
+  deriving Show
+
+-- | Identifiers for value handles
+type VHID = Int
+
+
```
Comment (jorisdral) [inline ouroboros-consensus/bench/backingstore-bench/Bench/Commands.hs:57]:
```suggestion
```

File: ouroboros-consensus/bench/backingstore-bench/Main.hs [hunk 3]
```diff
@@ -0,0 +1,163 @@
...
+  where
+    go :: [a] -> [[a]]
+    go [] = []
+    go xs = take n xs : groupsOfN n (drop n xs)
+
+{-------------------------------------------------------------------------------
+  Set up benchmark environment
+-------------------------------------------------------------------------------}
+
+data Env m ks vs d = Env {
```
Comment (jorisdral) [inline ouroboros-consensus/bench/backingstore-bench/Main.hs:135]: Document this type. Why do we need it? Why do we need the fields?

File: ouroboros-consensus/bench/backingstore-bench/Main.hs [hunk 4]
```diff
@@ -0,0 +1,163 @@
...
+  Main benchmarks
+-------------------------------------------------------------------------------}
+
+main :: IO ()
+main = defaultMain [ benchmarks ]
+
+benchmarks :: Benchmark
+benchmarks = bgroup "BackingStore" [
+      benchCmds "simpleCopy InMemory" bssInMem simpleCopy
+    , benchCmds "simpleCopy LMDB"     bssLMDB  simpleCopy
```
Comment (jorisdral) [inline ouroboros-consensus/bench/backingstore-bench/Main.hs:45]: Change them to tests

**Review by jasagredo — APPROVED** [review]

File: ouroboros-consensus/ouroboros-consensus.cabal [hunk 5]
```diff
@@ -748,3 +748,40 @@ benchmark mempool-bench
...
+    , ouroboros-consensus
+    , tasty
+    , QuickCheck
+    , tasty-bench
+    , tasty-quickcheck
+    , temporary
+
+  default-language: Haskell2010
+  ghc-options:
+    -Wall -Wcompat -Wincomplete-uni-patterns
```
[the remark this answers is not in the document]
Comment (jorisdral) [reply ouroboros-consensus/ouroboros-consensus.cabal:777]: I made a common stanza for benchmarks
